version: '3.8'
services:
  pgdb:
    image: postgres:13-alpine
    container_name: pgdb
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - pgdb_data:/var/lib/postgresql/data
      - postgres_logs:/logs
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      - DATABASE_URL
      - PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - pgdb

networks:
  app-network:
    driver: bridge

volumes:
  pgdb_data:
  postgres_logs:
